-- =====================================================
-- Arquitectura de mini cursillos / grupos de cursos
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.grupos_cursos (
  id_grupo_curso uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_cursillo uuid NOT NULL REFERENCES public.cursillos(id_cursillo) ON DELETE CASCADE,
  nombre text NOT NULL,
  descripcion text NULL,
  orden integer GENERATED BY DEFAULT AS IDENTITY,
  es_activo boolean NOT NULL DEFAULT true,
  requiere_password boolean NOT NULL DEFAULT false,
  password_hash text NULL,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fec_insercion timestamptz NULL,
  usu_insercion varchar NULL,
  fec_modificacion timestamptz NULL,
  usu_modificacion varchar NULL,
  CONSTRAINT grupos_cursos_nombre_not_blank CHECK (length(trim(nombre)) > 0)
);

ALTER TABLE public.grupos_cursos
  ADD COLUMN IF NOT EXISTS requiere_password boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS password_hash text NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'grupos_cursos_password_consistente'
      AND conrelid = 'public.grupos_cursos'::regclass
  ) THEN
    ALTER TABLE public.grupos_cursos
      ADD CONSTRAINT grupos_cursos_password_consistente
      CHECK (
        (requiere_password = false AND password_hash IS NULL)
        OR (requiere_password = true AND password_hash IS NOT NULL)
      );
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_grupos_cursos_nombre_cursillo
  ON public.grupos_cursos (id_cursillo, lower(trim(nombre)));

CREATE INDEX IF NOT EXISTS idx_grupos_cursos_cursillo_orden
  ON public.grupos_cursos (id_cursillo, es_activo, orden, nombre);

ALTER TABLE public.cursos
  ADD COLUMN IF NOT EXISTS id_grupo_curso uuid NULL
  REFERENCES public.grupos_cursos(id_grupo_curso) ON DELETE SET NULL;

ALTER TABLE public.cursos
  ADD COLUMN IF NOT EXISTS requiere_password boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS password_hash text NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'cursos_password_consistente'
      AND conrelid = 'public.cursos'::regclass
  ) THEN
    ALTER TABLE public.cursos
      ADD CONSTRAINT cursos_password_consistente
      CHECK (
        (requiere_password = false AND password_hash IS NULL)
        OR (requiere_password = true AND password_hash IS NOT NULL)
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_cursos_cursillo_grupo
  ON public.cursos (id_cursillo, id_grupo_curso);

CREATE OR REPLACE FUNCTION public.trg_prevent_direct_password_hash_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF COALESCE(current_setting('app.allow_password_hash_write', true), '') = 'on' THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW.password_hash IS NOT NULL THEN
      RAISE EXCEPTION 'password_hash solo puede configurarse mediante RPC segura';
    END IF;
  ELSIF NEW.password_hash IS DISTINCT FROM OLD.password_hash THEN
    RAISE EXCEPTION 'password_hash solo puede configurarse mediante RPC segura';
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS prevent_direct_grupo_password_hash_write ON public.grupos_cursos;
CREATE TRIGGER prevent_direct_grupo_password_hash_write
  BEFORE INSERT OR UPDATE OF password_hash ON public.grupos_cursos
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_prevent_direct_password_hash_write();

DROP TRIGGER IF EXISTS prevent_direct_curso_password_hash_write ON public.cursos;
CREATE TRIGGER prevent_direct_curso_password_hash_write
  BEFORE INSERT OR UPDATE OF password_hash ON public.cursos
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_prevent_direct_password_hash_write();

-- Backfill: cada cursillo con cursos existentes recibe un grupo General.
INSERT INTO public.grupos_cursos (id_cursillo, nombre, descripcion, orden, es_activo)
SELECT DISTINCT c.id_cursillo, 'General', 'Cursos existentes antes de la organizacion por grupos.', 0, true
FROM public.cursos c
WHERE c.id_cursillo IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.grupos_cursos gc
    WHERE gc.id_cursillo = c.id_cursillo
      AND lower(trim(gc.nombre)) = lower(trim('General'))
  );

UPDATE public.cursos c
SET id_grupo_curso = gc.id_grupo_curso
FROM public.grupos_cursos gc
WHERE c.id_grupo_curso IS NULL
  AND gc.id_cursillo = c.id_cursillo
  AND lower(trim(gc.nombre)) = lower(trim('General'));

-- Evita asignar un curso a un grupo que pertenece a otro cursillo.
CREATE OR REPLACE FUNCTION public.trg_validate_curso_grupo_cursillo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_grupo_cursillo uuid;
BEGIN
  IF NEW.id_grupo_curso IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT gc.id_cursillo
  INTO v_grupo_cursillo
  FROM public.grupos_cursos gc
  WHERE gc.id_grupo_curso = NEW.id_grupo_curso;

  IF v_grupo_cursillo IS NULL THEN
    RAISE EXCEPTION 'Grupo de curso no encontrado';
  END IF;

  IF v_grupo_cursillo <> NEW.id_cursillo THEN
    RAISE EXCEPTION 'El grupo seleccionado no pertenece al cursillo del curso';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS validate_curso_grupo_cursillo ON public.cursos;
CREATE TRIGGER validate_curso_grupo_cursillo
  BEFORE INSERT OR UPDATE OF id_cursillo, id_grupo_curso ON public.cursos
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_validate_curso_grupo_cursillo();

DROP TRIGGER IF EXISTS set_auditoria_campos ON public.grupos_cursos;
CREATE TRIGGER set_auditoria_campos
  BEFORE INSERT OR UPDATE ON public.grupos_cursos
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_set_auditoria_campos();

ALTER TABLE public.grupos_cursos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "grupos_cursos_select" ON public.grupos_cursos;
CREATE POLICY "grupos_cursos_select"
ON public.grupos_cursos
FOR SELECT
USING (
  public.has_cursillo_role(id_cursillo, 'ADMINISTRADOR')
  OR public.has_cursillo_role(id_cursillo, 'DOCENTE')
  OR (es_activo = true AND public.has_cursillo_role(id_cursillo, 'ESTUDIANTE'))
);

DROP POLICY IF EXISTS "grupos_cursos_insert_admin" ON public.grupos_cursos;
CREATE POLICY "grupos_cursos_insert_admin"
ON public.grupos_cursos
FOR INSERT
WITH CHECK (
  public.has_cursillo_role(id_cursillo, 'ADMINISTRADOR')
  OR public.has_cursillo_role(id_cursillo, 'DOCENTE')
);

DROP POLICY IF EXISTS "grupos_cursos_update_admin" ON public.grupos_cursos;
CREATE POLICY "grupos_cursos_update_admin"
ON public.grupos_cursos
FOR UPDATE
USING (
  public.has_cursillo_role(id_cursillo, 'ADMINISTRADOR')
  OR public.has_cursillo_role(id_cursillo, 'DOCENTE')
)
WITH CHECK (
  public.has_cursillo_role(id_cursillo, 'ADMINISTRADOR')
  OR public.has_cursillo_role(id_cursillo, 'DOCENTE')
);

DROP POLICY IF EXISTS "grupos_cursos_delete_admin" ON public.grupos_cursos;
CREATE POLICY "grupos_cursos_delete_admin"
ON public.grupos_cursos
FOR DELETE
USING (public.has_cursillo_role(id_cursillo, 'ADMINISTRADOR'));

DROP FUNCTION IF EXISTS public.rpc_list_grupos_cursos(uuid);
CREATE OR REPLACE FUNCTION public.rpc_list_grupos_cursos(p_id_cursillo uuid)
RETURNS TABLE(
  id_grupo_curso uuid,
  id_cursillo uuid,
  nombre text,
  descripcion text,
  orden integer,
  es_activo boolean,
  requiere_password boolean,
  total_cursos bigint,
  cursos_publicados bigint
)
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_is_staff boolean;
  v_is_student boolean;
BEGIN
  v_is_staff :=
    public.has_cursillo_role(p_id_cursillo, 'ADMINISTRADOR')
    OR public.has_cursillo_role(p_id_cursillo, 'DOCENTE');
  v_is_student := public.has_cursillo_role(p_id_cursillo, 'ESTUDIANTE');

  IF NOT (v_is_staff OR v_is_student) THEN
    RAISE EXCEPTION 'No autorizado para listar grupos de cursos';
  END IF;

  RETURN QUERY
  SELECT
    gc.id_grupo_curso,
    gc.id_cursillo,
    gc.nombre::text,
    gc.descripcion::text,
    gc.orden,
    gc.es_activo,
    gc.requiere_password,
    COUNT(c.id_curso)::bigint AS total_cursos,
    COUNT(c.id_curso) FILTER (WHERE c.es_publicado = true)::bigint AS cursos_publicados
  FROM public.grupos_cursos gc
  LEFT JOIN public.cursos c ON c.id_grupo_curso = gc.id_grupo_curso
  WHERE gc.id_cursillo = p_id_cursillo
    AND (
      v_is_staff
      OR (
        gc.es_activo = true
        AND EXISTS (
          SELECT 1
          FROM public.cursos c2
          WHERE c2.id_grupo_curso = gc.id_grupo_curso
            AND c2.es_publicado = true
        )
      )
    )
  GROUP BY gc.id_grupo_curso, gc.id_cursillo, gc.nombre, gc.descripcion, gc.orden, gc.es_activo, gc.requiere_password
  ORDER BY gc.orden ASC, gc.nombre ASC;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.rpc_list_grupos_cursos(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.rpc_set_grupo_curso_password(
  p_id_grupo_curso uuid,
  p_requiere_password boolean,
  p_password text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_id_cursillo uuid;
BEGIN
  SELECT id_cursillo
  INTO v_id_cursillo
  FROM public.grupos_cursos
  WHERE id_grupo_curso = p_id_grupo_curso;

  IF v_id_cursillo IS NULL THEN
    RAISE EXCEPTION 'Grupo de curso no encontrado';
  END IF;

  IF NOT (
    public.has_cursillo_role(v_id_cursillo, 'ADMINISTRADOR')
    OR public.has_cursillo_role(v_id_cursillo, 'DOCENTE')
  ) THEN
    RAISE EXCEPTION 'No autorizado para configurar la contrasena del grupo';
  END IF;

  IF p_requiere_password AND length(trim(coalesce(p_password, ''))) = 0 THEN
    RAISE EXCEPTION 'La contrasena del grupo es obligatoria';
  END IF;

  PERFORM set_config('app.allow_password_hash_write', 'on', true);

  UPDATE public.grupos_cursos
  SET
    requiere_password = p_requiere_password,
    password_hash = CASE
      WHEN p_requiere_password THEN crypt(p_password, gen_salt('bf'))
      ELSE NULL
    END
  WHERE id_grupo_curso = p_id_grupo_curso;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.rpc_set_grupo_curso_password(uuid, boolean, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.rpc_set_curso_password(
  p_id_curso uuid,
  p_requiere_password boolean,
  p_password text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_id_cursillo uuid;
  v_id_docente uuid;
  v_current_usuario uuid;
BEGIN
  SELECT c.id_cursillo, c.id_docente
  INTO v_id_cursillo, v_id_docente
  FROM public.cursos c
  WHERE c.id_curso = p_id_curso;

  IF v_id_cursillo IS NULL THEN
    RAISE EXCEPTION 'Curso no encontrado';
  END IF;

  v_current_usuario := public.current_id_usuario();

  IF NOT (
    public.has_cursillo_role(v_id_cursillo, 'ADMINISTRADOR')
    OR (public.has_cursillo_role(v_id_cursillo, 'DOCENTE') AND v_id_docente = v_current_usuario)
  ) THEN
    RAISE EXCEPTION 'No autorizado para configurar la contrasena del curso';
  END IF;

  IF p_requiere_password AND length(trim(coalesce(p_password, ''))) = 0 THEN
    RAISE EXCEPTION 'La contrasena del curso es obligatoria';
  END IF;

  PERFORM set_config('app.allow_password_hash_write', 'on', true);

  UPDATE public.cursos
  SET
    requiere_password = p_requiere_password,
    password_hash = CASE
      WHEN p_requiere_password THEN crypt(p_password, gen_salt('bf'))
      ELSE NULL
    END
  WHERE id_curso = p_id_curso;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.rpc_set_curso_password(uuid, boolean, text) TO authenticated;

DROP POLICY IF EXISTS "inscripciones_insert" ON public.inscripciones;
CREATE POLICY "inscripciones_insert"
ON public.inscripciones
FOR INSERT
WITH CHECK (
  id_usuario = public.current_id_usuario()
  AND EXISTS (
    SELECT 1
    FROM public.cursos c
    LEFT JOIN public.grupos_cursos gc ON gc.id_grupo_curso = c.id_grupo_curso
    WHERE c.id_curso = inscripciones.id_curso
      AND c.es_publicado = true
      AND c.requiere_password = false
      AND COALESCE(gc.requiere_password, false) = false
  )
);

CREATE OR REPLACE FUNCTION public.rpc_inscribirse_curso(
  p_id_curso uuid,
  p_password text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_id_usuario uuid;
  v_id_inscripcion uuid;
  v_curso record;
  v_password text;
BEGIN
  v_id_usuario := public.current_id_usuario();

  IF v_id_usuario IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  SELECT
    c.id_curso,
    c.id_cursillo,
    c.es_publicado,
    c.requiere_password AS curso_requiere_password,
    c.password_hash AS curso_password_hash,
    COALESCE(gc.requiere_password, false) AS grupo_requiere_password,
    gc.password_hash AS grupo_password_hash
  INTO v_curso
  FROM public.cursos c
  LEFT JOIN public.grupos_cursos gc ON gc.id_grupo_curso = c.id_grupo_curso
  WHERE c.id_curso = p_id_curso;

  IF v_curso.id_curso IS NULL THEN
    RAISE EXCEPTION 'Curso no encontrado';
  END IF;

  IF v_curso.es_publicado IS NOT TRUE THEN
    RAISE EXCEPTION 'El curso no esta publicado';
  END IF;

  IF NOT public.has_cursillo_role(v_curso.id_cursillo, 'ESTUDIANTE') THEN
    RAISE EXCEPTION 'No autorizado para inscribirse en este curso';
  END IF;

  v_password := trim(coalesce(p_password, ''));

  IF v_curso.curso_requiere_password THEN
    IF v_password = '' OR crypt(v_password, v_curso.curso_password_hash) <> v_curso.curso_password_hash THEN
      RAISE EXCEPTION 'Contrasena de curso incorrecta';
    END IF;
  ELSIF v_curso.grupo_requiere_password THEN
    IF v_password = '' OR crypt(v_password, v_curso.grupo_password_hash) <> v_curso.grupo_password_hash THEN
      RAISE EXCEPTION 'Contrasena de grupo incorrecta';
    END IF;
  END IF;

  SELECT i.id_inscripcion
  INTO v_id_inscripcion
  FROM public.inscripciones i
  WHERE i.id_usuario = v_id_usuario
    AND i.id_curso = p_id_curso
  LIMIT 1;

  IF v_id_inscripcion IS NOT NULL THEN
    RETURN v_id_inscripcion;
  END IF;

  INSERT INTO public.inscripciones (id_usuario, id_curso)
  VALUES (v_id_usuario, p_id_curso)
  RETURNING id_inscripcion INTO v_id_inscripcion;

  RETURN v_id_inscripcion;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.rpc_inscribirse_curso(uuid, text) TO authenticated;

DROP FUNCTION IF EXISTS public.rpc_get_cursos_reporte();
CREATE OR REPLACE FUNCTION public.rpc_get_cursos_reporte()
RETURNS TABLE(
  id_curso uuid,
  titulo text,
  id_grupo_curso uuid,
  nombre_grupo text
)
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT
    c.id_curso,
    c.titulo::text,
    c.id_grupo_curso,
    COALESCE(gc.nombre, 'Sin grupo')::text AS nombre_grupo
  FROM public.cursos c
  LEFT JOIN public.grupos_cursos gc ON gc.id_grupo_curso = c.id_grupo_curso
  WHERE public.has_cursillo_role(c.id_cursillo, 'ADMINISTRADOR')
     OR public.has_cursillo_role(c.id_cursillo, 'DOCENTE')
  ORDER BY COALESCE(gc.orden, 999999), COALESCE(gc.nombre, 'Sin grupo'), c.titulo;
$function$;

GRANT EXECUTE ON FUNCTION public.rpc_get_cursos_reporte() TO authenticated;

DROP FUNCTION IF EXISTS public.rpc_dashboard_estudiante(uuid);
CREATE OR REPLACE FUNCTION public.rpc_dashboard_estudiante(
  p_id_usuario uuid
)
RETURNS TABLE (
  id_curso uuid,
  titulo text,
  id_grupo_curso uuid,
  nombre_grupo text,
  total_lecciones bigint,
  lecciones_completadas bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
BEGIN
  RETURN QUERY
  SELECT
    c.id_curso,
    c.titulo,
    c.id_grupo_curso,
    COALESCE(gc.nombre, 'Sin grupo')::text AS nombre_grupo,
    COUNT(DISTINCT l.id_leccion)::bigint AS total_lecciones,
    COUNT(DISTINCT pl.id_leccion)::bigint AS lecciones_completadas
  FROM public.inscripciones i
  JOIN public.cursos c ON c.id_curso = i.id_curso
  LEFT JOIN public.grupos_cursos gc ON gc.id_grupo_curso = c.id_grupo_curso
  LEFT JOIN public.modulos m ON m.id_curso = c.id_curso
  LEFT JOIN public.lecciones l ON l.id_modulo = m.id_modulo
  LEFT JOIN public.progreso_lecciones pl ON pl.id_leccion = l.id_leccion
                                  AND pl.id_usuario = p_id_usuario
                                  AND pl.completado = true
  WHERE i.id_usuario = p_id_usuario
  GROUP BY c.id_curso, c.titulo, c.id_grupo_curso, gc.nombre, gc.orden
  ORDER BY COALESCE(gc.orden, 999999), COALESCE(gc.nombre, 'Sin grupo'), c.titulo;
END;
$$;

GRANT EXECUTE ON FUNCTION public.rpc_dashboard_estudiante(uuid) TO authenticated;

DROP FUNCTION IF EXISTS public.rpc_list_all_inscripciones(uuid);
CREATE OR REPLACE FUNCTION public.rpc_list_all_inscripciones(p_id_cursillo uuid)
RETURNS TABLE(
  id_inscripcion uuid,
  fecha_inscripcion timestamp with time zone,
  id_usuario uuid,
  nombres text,
  apellidos text,
  correo text,
  id_curso uuid,
  titulo_curso text,
  id_grupo_curso uuid,
  nombre_grupo text
)
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT (
    public.has_cursillo_role(p_id_cursillo, 'ADMINISTRADOR')
    OR public.has_cursillo_role(p_id_cursillo, 'DOCENTE')
  ) THEN
    RAISE EXCEPTION 'No autorizado: no tienes permisos para ver inscripciones de este cursillo';
  END IF;

  RETURN QUERY
  SELECT
    i.id_inscripcion,
    i.fecha_inscripcion,
    u.id_usuario,
    u.nombres::text,
    u.apellidos::text,
    u.correo::text,
    c.id_curso,
    c.titulo::text AS titulo_curso,
    c.id_grupo_curso,
    COALESCE(gc.nombre, 'Sin grupo')::text AS nombre_grupo
  FROM public.inscripciones i
  JOIN public.usuarios u ON u.id_usuario = i.id_usuario
  JOIN public.cursos c ON c.id_curso = i.id_curso
  LEFT JOIN public.grupos_cursos gc ON gc.id_grupo_curso = c.id_grupo_curso
  JOIN public.usuarios_cursillos uc
    ON uc.id_usuario = u.id_usuario
   AND uc.id_cursillo = c.id_cursillo
  JOIN public.roles r ON r.id_rol = uc.id_rol
  WHERE c.id_cursillo = p_id_cursillo
    AND UPPER(TRIM(r.nombre_rol)) = 'ESTUDIANTE'
  ORDER BY i.fecha_inscripcion DESC;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.rpc_list_all_inscripciones(uuid) TO authenticated;
